name: boozle
description: Student game for partying

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.1
  firebase_auth: ^0.4.3
  firebase_database: ^0.3.4
  flutter_color_picker: ^0.0.1
  logging: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/nyan_cat.gif
    - images/lake.jpg
